apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"